/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrar;

import BaseDatos.ConexionBD;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author SUCOSPP
 */
public class medidoresAdmin extends javax.swing.JFrame {

    /**
     * Creates new form telefonoAdmin
     */
    String ced = "";

    public medidoresAdmin(String cedula) {
        initComponents();
        ced = cedula;
    }
    ConexionBD conexion = new ConexionBD();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        medidortxt = new javax.swing.JTextField();
        lblcedula = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        medidorlist = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INGRESAR MEDIDORES");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mas (1).png"))); // NOI18N
        jButton1.setText("Ingresar Medidor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 104, -1, 35));
        getContentPane().add(medidortxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 56, 170, 30));

        lblcedula.setText("jLabel1");
        getContentPane().add(lblcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 12, -1, -1));

        jScrollPane1.setViewportView(medidorlist);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 56, -1, -1));

        jLabel1.setText("Medidores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 12, -1, -1));

        jLabel2.setText("Cédula");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 12, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//JOptionPane.showMessageDialog(this, ced);
        if (medidortxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un número de medidor", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            conexion.crearConexion();
            conexion.ejecutarSQL("insert into medidor (numero_medidor,personas_idpersonas) values ('" + medidortxt.getText() + "',(select idpersonas from personas where cedula='" + ced + "'))");
            JOptionPane.showMessageDialog(this, "Medidor ingresado correctamente", "Medidor Ingresado", JOptionPane.INFORMATION_MESSAGE);

        }
        rellenarDatos();
        medidortxt.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void rellenarDatos() {
        try {
            lblcedula.setText(ced);
            ResultSet datos;
            datos = conexion.ejecutarSQLSelect("select numero_medidor from personas inner join medidor on idpersonas=personas_idpersonas where cedula='" + ced + "'");
            DefaultListModel modelo = new DefaultListModel();
            while (datos.next()) {
                modelo.addElement(datos.getString("numero_medidor"));

            }
            medidorlist.setModel(modelo);

        } catch (SQLException ex) {
            Logger.getLogger(medidoresAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        rellenarDatos();

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JList<String> medidorlist;
    private javax.swing.JTextField medidortxt;
    // End of variables declaration//GEN-END:variables
}
