/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrar;

import consultas.*;
import BaseDatos.ConexionBD;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SUCOSPP
 */
public class tomarLista extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public tomarLista() {
        initComponents();
    }
    ConexionBD conexion = new ConexionBD();

    public void cargarDatos(String where) {
        try {

            DefaultTableModel modelo = (DefaultTableModel) jTabla.getModel();

            ResultSet datos = conexion.ejecutarSQLSelect("select count(*) as contar from Lista where Month(fecha_asistencia)=month(CURDATE())");
            int cuenta = 0;
            while (datos.next()) {
                cuenta = Integer.parseInt(datos.getString("contar"));

            }
            if (cuenta == 0) {
                datos = conexion.ejecutarSQLSelect("select nombres as nombres ,cedula from personas " + where);

                ResultSetMetaData Mdatos = datos.getMetaData();

                //modelo.setRowCount(0);
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    modelo.removeRow(i);
                }
                /* while(columna<=Mdatos.getColumnCount()){
            modelo.addColumn(Mdatos.getColumnName(columna));
            columna++;
            }
            modelo.addColumn("Asisitió");
                 */

                while (datos.next()) {
                    modelo.addRow(new Object[]{datos.getString("nombres"), datos.getString("cedula"), new Boolean(false)});

                }
            } else {

                datos = conexion.ejecutarSQLSelect("select nombres,cedula,case when asiste=1 then 'true' else 'false' end as asiste  from Lista inner join personas on idpersonas=personas_idpersonas where Month(fecha_asistencia)=month(CURDATE())" + where);

                modelo.setRowCount(0);
                for (int i = 0; i < modelo.getRowCount(); i++) {
                    modelo.removeRow(i);
                }
                /* while(columna<=Mdatos.getColumnCount()){
            modelo.addColumn(Mdatos.getColumnName(columna));
            columna++;
            }
            modelo.addColumn("Asisitió");
                 */

                while (datos.next()) {
                    modelo.addRow(new Object[]{datos.getString("nombres"), datos.getString("cedula"), datos.getBoolean("asiste")});

                }

            }

            //jTabla.setModel(modelo);
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(tomarLista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TOMAR LISTA ASAMBLEA");
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabla.setAutoCreateRowSorter(true);
        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cédula", "Asistió"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 20, 681, 522));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        jButton2.setText("Guardar Asistencia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 550, 250, 41));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarDatos("");        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            conexion.cerrarConexion();        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Telefonos.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Está seguro que desea guardar los cambios", "Guardar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {        // a.ejecutarSQL("UPDATE producto SET Descripcion='"+jDescripcion.getText()+"', Precio = "+jPrecio.getText()+", disponible="+jCantidad.getText()+" WHERE idProducto="+id+";") ;
            conexion.crearConexion();
            try {

                conexion.ejecutarSQL("delete from Lista where Month(fecha_asistencia)=month(CURDATE())");

                ResultSet datos = conexion.ejecutarSQLSelect("SELECT CURDATE() as fecha");
                String fecha = "";
                while (datos.next()) {

                    fecha = datos.getString("fecha");

                }
                for (int i = 0; i < jTabla.getRowCount(); i++) {
                    int asiste = 0;
                    if (Boolean.valueOf(jTabla.getValueAt(i, 2).toString())) {
                        asiste = 1;
                    }
                    //System.out.print(jTabla.getValueAt(i, 2).toString());
                    if (jTabla.getValueAt(i, 1) != null) {
                        // System.out.print(jTabla.getValueAt(i, 1).toString());

                        conexion.ejecutarSQL("insert into Lista(fecha_asistencia,Asiste,Personas_idPersonas) values ('" + fecha + "'," + asiste + ",(select idpersonas from personas where cedula ='" + jTabla.getValueAt(i, 1).toString() + "' or nombres ='" + jTabla.getValueAt(i, 0).toString() + "'))");
                    }
                }

                JOptionPane.showMessageDialog(this, "ingresado Correctamente", "Ingresado", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(tomarLista.class.getName()).log(Level.SEVERE, null, ex);
            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tomarLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tomarLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tomarLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tomarLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tomarLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
}
