/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultas;

import BaseDatos.ConexionBD;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SUCOSPP
 */
public class Lecturas extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Lecturas() {
        initComponents();
    }
        ConexionBD conexion = new ConexionBD();
        DefaultTableModel modelo = new DefaultTableModel();

public  void cargarDatos(String where){
     try {
           
         
            ResultSet datos=conexion.ejecutarSQLSelect("select Nombres,Cedula,fecha_lectura,lectura from personas inner join lecturas on idpersonas=personas_idpersonas "+ where);
            ResultSetMetaData Mdatos=datos.getMetaData();
         
            modelo.setColumnCount(0);
            modelo.setRowCount(0);
            int columna=1;
            
            while(columna<=Mdatos.getColumnCount()){
            modelo.addColumn(Mdatos.getColumnName(columna));
            columna++;
            }
            
            while(datos.next()){

                modelo.addRow(new Object[]{datos.getString("nombres"),datos.getString("cedula"),datos.getString("fecha_lectura"),datos.getString("lectura")});
                
            }
            
            
            jTabla.setModel(modelo);
// TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Lecturas.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buscatxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fechaCalendar = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSULTAR LECTURAS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 681, 390));

        jLabel1.setText("Buscar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 30, -1, -1));

        buscatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscatxtKeyReleased(evt);
            }
        });
        getContentPane().add(buscatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 25, 138, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/goma-de-borrar.png"))); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 24, 110, -1));
        getContentPane().add(fechaCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 77, 170, 40));

        jLabel3.setText("Fecha Lectura");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 77, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/busqueda.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 77, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
cargarDatos("");        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            conexion.cerrarConexion();        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Telefonos.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void buscatxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscatxtKeyReleased
        cargarDatos("where nombres like '%"+buscatxt.getText()+"%' or cedula like '%"+buscatxt.getText()+"%'");        // TODO add your handling code here:
    }//GEN-LAST:event_buscatxtKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cargarDatos("");
        buscatxt.setText("");
fechaCalendar.setDate(null);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(fechaCalendar.getDate()==null){
                    JOptionPane.showMessageDialog(this, "Debe ingresar una fecha", "Error", JOptionPane.ERROR_MESSAGE);

}else{
        cargarDatos("where year(fecha_lectura)='" + String.valueOf(Integer.parseInt(new SimpleDateFormat("yyyy").format(fechaCalendar.getDate()))) + "' and month(fecha_lectura)='" + String.valueOf(Integer.parseInt(new SimpleDateFormat("MM").format(fechaCalendar.getDate()))) + "' and ( nombres like '%"+buscatxt.getText()+"%' or cedula like '%"+buscatxt.getText()+"%') ");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lecturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lecturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lecturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lecturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lecturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscatxt;
    private com.toedter.calendar.JDateChooser fechaCalendar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    // End of variables declaration//GEN-END:variables
}
